version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: chamas
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: chamas

	chamas:
		build: .
		image: chamaconekt/chamas
		links:
		- postgres
		container_name: chamas
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- chamas
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/chamas-nginx/nginx.conf
		depends_on:
			- chamas
		ports:
			- 80:80
		volumes_from:
			- chamas

volumes:
	chamas-static-files:
		driver:local